### ISSUE TITLE
ModuleNotFoundError: No module named 'regex'

### ISSUE THREAD

**Issue by dimpase** [Martin-Seysen/mmgroup#3]
This happens on Linux with Python 3.9. A missing dependency?

**Comment by fingolfin** [comment]
Just a note (I am not claiming this disputes the issue, just wanted to point it out): The manual has a long list of dependencies, including regex, numpy, cython, ...

**Comment by dimpase** [comment]
it's a documentation bug - one has to run `pip3 install -r requirements.txt -U` in the root directory of the package to get this right.
(running pip without -U means one needs to have admin rights, by the way)

**Comment by dimpase** [comment]
As the package intself is not in `requirements.txt`, one will need another pip run to build the package itself. I'd suggest
```diff
--- a/requirements.txt
+++ b/requirements.txt
@@ -5,4 +5,4 @@ regex
 pytest
 sphinx>=2.0
 sphinxcontrib.bibtex
-
+mmgroup
```
to do everything in one go. 

PS. Python packaging is much harder than GAP packaging, or even any packaging IMHO... :-)

**Comment by Martin-Seysen** [comment]
I'm just a bit concerned about a chicken-egg problem if the construction of something requires that thing already to exist.
But if there is any evidence that this is not a real problem here then I will of course follow your suggestion.

**Comment by dimpase** [comment]
"Requires" means "download if needed, build if needed", so it's not chicken-egg IMHO.

**Comment by fingolfin** [comment]
@dimpase is a SageMath developer and has a lot of experience with Python (certainly more than I have)

**Comment by dimpase** [comment]
fixed
