### ISSUE TITLE
Command '['/usr/bin/python3', 'codegen_mat24.py']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by dimpase** [Martin-Seysen/mmgroup#4]
After fixing #3 by installing regex, I get the above error (Linux, Python 3.9). Please see complete log below:

[mmg.log](https://github.com/Martin-Seysen/mmgroup/files/9606807/mmg.log)

**Comment by Martin-Seysen** [comment]
The names of some headers, including './src/mmgroup/dev/generators/mmgroup_generators.h', were missing in file MANIFEST.in.
Since I always use 'python setup.py  build_ext --inplace ...',  I have never seen this problem.
I have added the missing path names to MANIFEST.in. Hope this helps.

**Comment by dimpase** [comment]
`python3 setup.py build_ext --inplace` seems to work (one cannot assume `python` is even present on a system; if your code is python3, just use python3 everywhere. `pip3` still does not. (I guess, it's not in-place by default?)

There is a way to pass extra options to `pip3` (again, there need not be any `pip`, only `pip3`)

**Comment by dimpase** [comment]
Calling `python3` as above ends with
```
src/mmgroup/tests/test_orders/check_monster_orders.py:13: in <module>
    from scipy.stats import chisquare
E   ModuleNotFoundError: No module named 'scipy'
======================================================== short test summary info ========================================================
ERROR src/mmgroup/tests/test_axes/test_display_axes.py
ERROR src/mmgroup/tests/test_gen_xi/test_gen_type2.py
ERROR src/mmgroup/tests/test_gen_xi/test_gen_type3.py
ERROR src/mmgroup/tests/test_gen_xi/test_gen_type4.py
ERROR src/mmgroup/tests/test_gen_xi/test_leech2_type.py
ERROR src/mmgroup/tests/test_gen_xi/test_reduce.py
ERROR src/mmgroup/tests/test_gen_xi/test_reduce_n.py
ERROR src/mmgroup/tests/test_involutions/test_xsp2_trace.py
ERROR src/mmgroup/tests/test_mm_op/test_io.py
ERROR src/mmgroup/tests/test_orders/test_chisqu_orders.py
ERROR src/mmgroup/tests/test_orders/test_monster_orders.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 11 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================== 184 deselected, 11 errors in 4.85s ===================================================

Subprocess 'pytest' has failed!
```

- it seems that `scipy` is needed for testing, so should be in `requirements.txt`, too

**Comment by Martin-Seysen** [comment]
I have added 'scipy' and 'mmgroup' to file 'requirements.txt'. Does everything now work as expected, so that I can close this issue?

**Comment by dimpase** [comment]
Could you put in README the list of commands to    build and test, which works for you?

**Comment by dimpase** [comment]
OK, this looks more or less done.
