### ISSUE TITLE
Building documentation on readthedocs fails

### ISSUE THREAD

**Issue by Martin-Seysen** [Martin-Seysen/mmgroup#7]
Building documentation on readthedocs fails, see

https://readthedocs.org/projects/mmgroup/builds/18163156/

File 'requirements.txt' in this project now requires numpy version >= 1.23;
but the latest numpy version avaliable on readthedocs appears to be  1.21.6.

**Comment by dimpase** [comment]
That's cause you use python3.7 there, and for numpy 1.23 you need 3.8.

**Comment by dimpase** [comment]
not sure where python3.7 there comes from, it's pretty old nowadays

**Comment by dimpase** [comment]
here is one way to use python3.9 instead: https://docs.readthedocs.io/en/stable/config-file/v2.html#build-beta-specification

**Comment by Martin-Seysen** [comment]
This fixes the bug in the generation of the documentation on readthedocs, thank you.
