### ISSUE TITLE
computing with Y-presentation for M?

### ISSUE THREAD

**Issue by dimpase** [Martin-Seysen/mmgroup#8]
I wonder whether your package may be used for this. It might be useful for extending work I did in 
https://doi.org/10.1016/j.aim.2017.03.029

**Comment by Martin-Seysen** [comment]
I just had a quick glance at your paper. Do you need generators of  the Y_443 presentation of the Monster in terms of the generators in this project, (and, may be, also vice versa)? At the moment I have no idea how to compute such generators. I think one has to embed a large portion of the Y_443 presentation into a more accessible subgroup of the Monster.

Here is a quick overview of what I can do in the project:

- Computing the order of an element
- Given two involutions a, b in the same class,  finding an x with  x^-1 * a * x = b
- Fast computation of the real degree-196883 character of an element centralizing
  a  **known**  2B involution
- Generating uniform random elements of  some 2-local subroups
- Generating an (almost) uniform random element of the Monster
- Almost doable: coset decomposition  M / 2.B / 2^(2+22).Co_2

**Comment by dimpase** [comment]
> Do you need generators of the Y_443 presentation of the Monster in terms of the generators in this project, (and, may be, also vice versa)?

yes. Various subgroups of Y_443 are described on p.233 of Atlas of Finite Groups. What generators are used by the project?

**Comment by Martin-Seysen** [comment]
I stay very close to Conway's construction of the Monster. The essential information about my generators is given here:

https://mmgroup.readthedocs.io/en/stable/api.html#module-mmgroup.mm_group

A kind of rewrite of Conway's paper explaining the choice of my generators is given here:

https://arxiv.org/abs/2002.10921

**Comment by Martin-Seysen** [comment]
The follwing paper may be helpful:

https://reader.elsevier.com/reader/sd/pii/S0021869313000410?token=12895C2E00FA8F012A3EF12801CC716D8A74366827C9C20B5DD07642F76C8FEFAD024EC64197D1E57954E0930A5803C2&originRegion=eu-west-1&originCreation=20220926203051

**Comment by dimpase** [comment]
Thanks, this looks useful.

**Comment by Martin-Seysen** [comment]
There is now a (yet poorly documented) application 'Y555' in the source distribution that maps the Coxeter group Y555 to the BiMonster. I could check e.g. the spider relation in Y555. I hope I can finish the documentation within this year.  Ideas for the implementation are taken from [Nor02] and [Far12], with citations as in

https://mmgroup.readthedocs.io/en/latest/api.html#version-history

Is there still any interest in porting the project to GAP or SAGE?

**Comment by dimpase** [comment]
Nice - at the moment I'd rather think how to use your code in research (too much Sage and GAP for me now :-))
But yes, inclusion into Sage should not be too hard.

**Comment by dimpase** [comment]
You might probably simplify dealing with the projective plane of order 3, usually denoted $PG(2,3)$, by using [SymPy permutation groups](https://docs.sympy.org/latest/modules/combinatorics/perm_groups.html?highlight=groups#module-sympy.combinatorics.perm_groups)

**Comment by dimpase** [comment]
If I have some words in the 26 generators, can your code verify a supplied relation between them - as a relation in the subgroup of $(\mathbb{M}\times\mathbb{M}).2$ they generate?

**Comment by Martin-Seysen** [comment]
Yes, sure!

For verifying e.g. the famous spider relation you just have to code:

from bimm import BiMM, P3_BiMM
spider = ['a', 'b1', 'c1', 'a', 'b2', 'c2', 'a', 'b3', 'c3'] * 10  # ATLAS notation for the Y_555 generators
# An entry in that list may be anything that is accepted 
# by the constructor of class P3_node in module inc_p3.py.
assert P3_BiMM(spider) == BiMM(1)

Remark:
At the moment you have to compile the source distribution, install it, and copy the python scripts from
subdirectory applications/Y555 to your working directory.
All this is yet experimental. In a future version class BiMM and function P3_BiMM may be part of the distribution.

**Comment by dimpase** [comment]
As far as I understand, any automorphism $\phi$ of the Y555 diagram lift to an automorphism $\Phi$ of PG(2,3). For $\Phi$, one can take, for each of its orbits on the 26 elements, product of the corresponding generators of Bimonster. I wonder whether these products generate the same subgroup of Bimonster as these that lie on the Y555 diagram.
E.g. if $\phi^2=1$ then it fixes one "leg" of Y555, so there are 6 length 1 orbits of $\Phi$ there, and 5 length 2 orbits.
As every generator outside of Y555 in PG(2,3) is redundant, it's natural to conjecture that the products over all the orbits are like this, too.

**Comment by Martin-Seysen** [comment]
There is a natural embedding from $\phi$ and from its lift $\Phi$ into the subgroup $\mathbb{M} \times \mathbb{M}$ of the Bimonster. If $\phi$  is the leg-swapping automorphism (with $\phi^2=1$) then the image of $\phi$ in $\mathbb{M} \times \mathbb{M}$ is a pair of 2A involutions in the diagonal of  in $\mathbb{M} \times mathbb{M}$.

The products of the generators in the orbits of $\phi$ centralize the  image of   $\phi$ in $\mathbb{M} \times \mathbb{M}$. So your question can probably be answered by a calculation in the Baby Monster (which is the cenralizer of a 2A involution).

At present my computation of image of $\phi$ contains a few unpleasent technicalities which will disappear after integrating my class BiMM (modelling the Bimonster) and its friends into the main project.

**Comment by dimpase** [comment]
> the image of $\phi$ ... is a pair of 2A involutions...

I don't understand how the image can be a pair. Where is the embedding you mentioned described?

Is it known that the products of the generators in the orbits of $\phi$ generate BM? (or, maybe, something like BMxBM ?)

**Comment by Martin-Seysen** [comment]
The image of $\phi$ in $\mathbb{M} \times \mathbb{M}$ is $\imath \times \imath$ for some 2A involution $\imath \in \mathbb{M}$. Norton [Nor02] gives a presentation for $\mathbb{M} \times \mathbb{M} \times L_3(3)$, where the generators are derived from the 26 nodes of the projective plane $P3$ and from the  automorphism group $L_3(3)$ of  $P3$ . The relation in eq. (8) in  [Nor02] kills the factor  $L_3(3)$; thus embedding the automorphism group $L_3(3)$ into  $\mathbb{M} \times \mathbb{M}$.

I dont't know which group is generated by the products of the generators in the orbits of $\phi$. One can explore this group e.g. by calculating orders of many elements in that group. One may also project elements of even length to one of the copies of   $\mathbb{M}$ in  $\mathbb{M} \times \mathbb{M}$, and try to find standard generatrs of the Baby Monster. But this appears to be a lengthy calculation.

**Comment by Martin-Seysen** [comment]
I computed 1000 ramdom samples from the intersection $G$ of the subgroup  $\mathbb{M} \times \mathbb{M}$ with the subgroup of the Bimonster generated by $a, b_1, c_1, d_1, e_1, f_1, b_2 b_3, c_2 c_3, d_2 d_3, e_2 e_2, f_2 f_3$. The distribution of the orders of the first factor of  these elements (in $\mathbb{M} \times \mathbb{M}$) is similar to the expected distibution of orders of elements of 2.B, where B is the Baby Monster. See module ``legswap.py`` in directory ``applications.Y555``.  For the actual computation I have factored $G$ by the image of  $\phi$ in $\mathbb{M} \times \mathbb{M}$, which is in the center of $G$.

**Comment by dimpase** [comment]
Nice! Can you check with the same method that $f_1$ and $f_2f_3$ are redundant, as generators of the group generated by the fixed points of the legswap involution?
(which is, as far as I understand, has $G$ as its index 2 subgroup)

I understand that your sampling involved words in $a$, $b_1$,..., $f_1$, $b_2b_3$,
...,  $f_2f_3$ - you probably could just filter out words involving $f_k$'s.

**Comment by dimpase** [comment]
One can certainly try to mimic the $PG(2,3)$ business for the legswap case; a legswap fixes 5 points and 5 lines of $PG(2,3),$ so in the new graph one will have $2\times (5+(13-5)/2)=18$ vertices, and some edges will double. You'll have a subgraph with vertices, in order as on the 1st picture below $f_1,...,b_1,a,b_2 b_3,...,f_2 f_3$:
```
o-o-o-o-o-o=o-o-o-o-o
  o-o-o-o-o=o-o-o-o
```
and the conjecture is that you'd generate all the 18 vertices by $e_1,...,b_1,a,b_2 b_3,...,e_2 e_3$ (the 2nd subgraph above).
A legswap has a special non-incident vertex-line pair $(p,L)$ in $PG(2,3)$, so that all points on $L$ and all lines through $p$ are fixed - I'm not sure what role, if any, they should play in the new graph. 

But before going this route, it would be nice to confirm that the intuition about the redundancy is right, by a computation like I suggested above.

**Comment by Martin-Seysen** [comment]
The new version of ``legswap.py`` confirms the intuition that generators $f_1$ and $f_2 f_3$ are redundant. It computes the distributions of the orders of both factors of the subgroup $G$ of $\mathbb{M} \times \mathbb{M}$ (generated by $a, b_1, c_1, d_1, e_1,  b_2 b_3, \ldots, e_2 e_3$) from 1000 samples. After factoring out the center of order $2$ of $2.B$, both distributions resemble the distribution of the orders of the elements of the Baby Monster $B$. The script ``legswap.py`` also displays some orders of pairs $g_1, g_2$, where $g = (g_1, g_2) \in G \subset \mathbb{M} \times \mathbb{M}$. This supports the intuition that $G$ is equal to $2.B \times 2.B$, i.e $G$ is not contained in some kind of diagonal of  $2.B \times 2.B$.

**Comment by Martin-Seysen** [comment]
The latest release mmgroup 0.0.12 contains functions for mapping the Coxeter group Y_555 onto the Bimonster in module mmgroup.bimm. For documentation see
https://mmgroup.readthedocs.io/en/latest/api.html#module-mmgroup.bimm.readme

So I think we can close this issue now.

**Comment by dimpase** [comment]
OK, I'll open another issue if I need help with these, or/and to work on more related functionality.

**Comment by dimpase** [comment]
I've just tested your new release on GitHub's Codespaces, all "not slow" pytest tests pass there.

**Comment by Martin-Seysen** [comment]
Thank you for testing my package. You are always welcome to ask me qustions about it, eitther via github or directly via e-mail.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Dima Pasechnik ***@***.***> Datum: 12.01.23  14:15  (GMT+01:00) An: Martin-Seysen/mmgroup ***@***.***> Cc: Martin-Seysen ***@***.***>, Comment ***@***.***> Betreff: Re: [Martin-Seysen/mmgroup] computing with Y-presentation for M?
  (Issue #8) 
Closed #8 as completed.
